=== tkucner/rose/confs/input_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/product.schema.json",
  "title": "Configuration",
  "description": "Configuration of ros running file",
  "type": "object",
  "properties": {
    "input_map": {
      "description": "path to a png file contianing map to be evaluated",
      "type": "string",
      "default": {}
    },
    "map_description": {
      "type": "string",
      "description": "Free text for describing used map",
      "default": {}
    },
    "peak_extraction_parameters": {
      "type": "object",
      "description": "parameters used for extraction of strucutre from a mpa",
      "properties": {
        "peak_height": {
          "type": "number",
          "default": {}
        },
        "smooth_histogram": {
          "type": "boolean",
          "default": {}
        },
        "sigma": {
          "type": "number",
          "default": {}
        }
      }
    },
    "filtering_parameters": {
      "type": "object",
      "description": "parmeters used to filter the desired pixels in the map",
      "properties": {
        "filter_level": {
          "type": "number",
          "default": {}
        }
      }
    },
    "visualisation_flags": {
      "type": "object",
      "description": "flags decideing what is going to be shown",
      "properties": {
        "Binary map": {
          "type": "boolean",
          "default": false
        },
        "FFT Spectrum": {
          "type": "boolean",
          "default": false
        },
        "Unfolded FFT Spectrum": {
          "type": "boolean",
          "default": false
        },
        "FFT Spectrum Signal": {
          "type": "boolean",
          "default": false
        },
        "FFT Spectrum Noise": {
          "type": "boolean",
          "default": false
        },
        "Map Reconstructed Signal": {
          "type": "boolean",
          "default": false
        },
        "Map Reconstructed Noise": {
          "type": "boolean",
          "default": false
        },
        "Map Scored Good": {
          "type": "boolean",
          "default": false
        },
        "Map Scored Bad": {
          "type": "boolean",
          "default": false
        },
        "Map Scored Diff": {
          "type": "boolean",
          "default": false
        },
        "Map Split Good": {
          "type": "boolean",
          "default": false
        },
        "FFT Map Split Good": {
          "type": "boolean",
          "default": false
        },
        "Side by Side": {
          "type": "boolean",
          "default": false
        },
        "Histogram of pixels quality": {
          "type": "boolean",
          "default": false
        },
        "Histogram of scaled pixels quality": {
          "type": "boolean",
          "default": false
        },
        "Simple Filtered Map": {
          "type": "boolean",
          "default": false
        },
        "FFT spectrum with directions": {
          "type": "boolean",
          "default": false
        },
        "Map with directions": {
          "type": "boolean",
          "default": false
        },
        "Partial Scores": {
          "type": "boolean",
          "default": false
        },
        "Partial Reconstructs": {
          "type": "boolean",
          "default": false
        },
        "Threshold Setup with Clusters": {
          "type": "boolean",
          "default": false
        },
        "Cluster Filtered Map": {
          "type": "boolean",
          "default": false
        },
        "Map with walls": {
          "type": "boolean",
          "default": false
        },
        "Map with slices": {
          "type": "boolean",
          "default": false
        },
        "Wall lines from mbb": {
          "type": "boolean",
          "default": false
        },
        "Labels and Raw map": {
          "type": "boolean",
          "default": false
        },
        "Raw line segments": {
          "type": "boolean",
          "default": false
        },
        "Clustered line segments": {
          "type": "boolean",
          "default": false
        },
        "Short wall lines from mbb": {
          "type": "boolean",
          "default": false
        },
        "Short wall lines over original map": {
          "type": "boolean",
          "default": false
        },
        "Map and peaks": {
          "type": "boolean",
          "default": false
        },
        "evaluation output": {
          "type": "boolean",
          "default": false
        }
      },
      "default": {}
    }
  },
  "additionalProperties": false,
  "default": {
  }
}

=== tkucner/rose/confs/input_2.json
{
  "input_map": "/home/tzkr/python_workspace/HouseExpo/experiments/map_id_100/ea41bd11b5c0b769558a620734451d99_obs_num_0.0_slamErr_linear_0.0_slamErr_angular_0.0_laser_noise_0.png",
  "map_description": "Perfect simple map from house expo examples",
  "peak_extraction_parameters": {
    "peak_height": 0.2,
    "smooth_histogram": true,
    "sigma": 0.5
  },
  "filtering_parameters": {
    "filter_level": 0.18
  },
  "visualisation_flags": {
    "Binary map": false,
    "Unfolded FFT Spectrum": false,
    "Map with directions": false,
    "Map with walls": false,
    "Wall lines from mbb": false,
    "Short wall lines from mbb": false,
    "Short wall lines over original map": true,
    "Map with slices": false,
    "Map Scored Good": false
  }
}

=== tkucner/rose/test_map.json
{
  "input_map": "test_map.png",
  "map_description": "map of real building from Freiburg",
  "peak_extraction_parameters": {
    "peak_height": 0.05,
    "smooth_histogram": true,
    "sigma": 0.5
  },
  "filtering_parameters": {
    "filter_level": 0.18
  },
  "visualisation_flags": {
    "Binary map": false,
    "Unfolded FFT Spectrum": true,
    "Map with directions": true,
    "Map with walls": false,
    "Wall lines from mbb": false,
    "Map with slices": false,
    "Map Scored Good": true,
    "FFT spectrum with directions": true,
    "FFT Spectrum Signal": true
  }
}

=== tkucner/rose/confs/input_5.json
{
  "input_map": "/home/tzkr/Data/MQ/2D_occ_maps/freiburg_building101.png",
  "map_description": "map of real building from Freiburg",
  "peak_extraction_parameters": {
    "peak_height": 0.05,
    "smooth_histogram": true,
    "sigma": 0.5
  },
  "filtering_parameters": {
    "filter_level": 0.18
  },
  "visualisation_flags": {
    "Binary map": false,
    "Unfolded FFT Spectrum": false,
    "Map with directions": false,
    "Map with walls": false,
    "Wall lines from mbb": false,
    "Short wall lines from mbb": false,
    "Short wall lines over original map": false,
    "Map with slices": false,
    "Map Scored Good": false
  }
}

=== tkucner/rose/confs/orkla_2021_03_04.json
{
  "input_map": "/home/tzkr/python_workspace/rose/Maps/output.png",
  "map_description": "map of real building from Freiburg",
  "peak_extraction_parameters": {
    "peak_height": 0.05,
    "smooth_histogram": true,
    "sigma": 0.5
  },
  "filtering_parameters": {
    "filter_level": 0.18
  },
  "visualisation_flags": {
    "Binary map": true,
    "Unfolded FFT Spectrum": false,
    "Map with directions": true,
    "Map with walls": true,
    "Wall lines from mbb": true,
    "Short wall lines from mbb": true,
    "Short wall lines over original map": true,
    "Map with slices": true,
    "Map Scored Good": false,
    "evaluation output": false,
    "Raw line segments": true
  }
}

=== tkucner/rose/input_4.json
{
  "input_map": "/home/tzkr/Data/MQ/2D_occ_maps/fr101.good.png",
  "map_description": "map of real building from Freiburg",
  "peak_extraction_parameters": {
    "peak_height": 0.2,
    "smooth_histogram": true,
    "sigma": 0.5
  },
  "filtering_parameters": {
    "filter_level": 0.18
  },
  "visualisation_flags": {
    "Binary map": false,
    "Unfolded FFT Spectrum": true,
    "Map with directions": false,
    "Map with walls": false,
    "Wall lines from mbb": false,
    "Short wall lines from mbb": false,
    "Short wall lines over original map": true,
    "Map with slices": false,
    "Map Scored Good": false
  }
}
