=== tkucner/rose/input_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://example.com/product.schema.json",
  "title": "Configuration",
  "description": "Configuration of rose running file",
  "type": "object",
  "properties": {
    "input_map": {
      "description": "path to a png file containing map to be evaluated",
      "type": "string",
      "default": {}
    },
    "map_description": {
      "type": "string",
      "description": "Free text for describing used map",
      "default": {}
    },
    "fft_filtering": {
      "type": "object",
      "description": "parameters used for extraction of strucutre from a mpa",
      "properties": {
        "peak_height": {
          "type": "number",
          "default": {}
        },
        "smooth_histogram": {
          "type": "boolean",
          "default": true
        },
        "sigma": {
          "type": "number",
          "default": 3
        },
        "angle_threshold": {
          "type": "number",
          "default": 0.01
        },
        "window_width": {
          "type": "integer",
          "default": 1
        },
        "quality_threshold": {
          "type": "number",
          "default": -1
        }
      }
    },
    "visualisation": {
      "type": "object",
      "description": "flags deciding what is going to be shown",
      "properties": {
        "Save path": {
          "type": "string",
          "default": ""
        },
        "Show plots": {
          "type": "boolean",
          "default": false
        },
        "Input map": {
          "type": "boolean",
          "default": false
        },
        "Binary map": {
          "type": "boolean",
          "default": false
        },
        "Frequency image": {
          "type": "boolean",
          "default": false
        },
        "Frequency image with dominant directions": {
          "type": "boolean",
          "default": false
        },
        "Frequency image with filter": {
          "type": "boolean",
          "default": false
        },
        "Filter": {
          "type": "boolean",
          "default": false
        },
        "Filtered frequency image": {
          "type": "boolean",
          "default": false
        },
        "Polar frequency image": {
          "type": "boolean",
          "default": false
        },
        "Polar frequency histogram": {
          "type": "boolean",
          "default": false
        },
        "Polar frequency image and histogram": {
          "type": "boolean",
          "default": false
        },
        "Reconstructed map": {
          "type": "boolean",
          "default": false
        },
        "Scored map": {
          "type": "boolean",
          "default": false
        },
        "Filtered map overlay": {
          "type": "boolean",
          "default": false
        },
        "Filtered map final": {
          "type": "boolean",
          "default": false
        },
        "Cell histogram": {
          "type": "boolean",
          "default": false
        },
        "Map with directions": {
          "type": "boolean",
          "default": false
        },
        "Map with long wall lines": {
          "type": "boolean",
          "default": false
        },
        "Separated wall directions": {
          "type": "boolean",
          "default": false
        }
      },
      "default": {}
    }
  },
  "additionalProperties": false,
  "default": {
  }
}

=== tkucner/rose/lines.json
{
  "input_map": "lines.png",
  "map_description": "three simple lines",
  "fft_filtering": {
    "peak_height": 0.05,
    "smooth_histogram": true,
    "sigma": 0.5,
    "window_width": 5,
    "quality_threshold": 0.18,
    "angle_threshold": 0.5
  },
  "visualisation": {
    "Save path": "/home/tzkr/Experiments/ROSE/2021/testing",
    "Input map": true,
    "Binary map": true,
    "Frequency image": true,
    "Frequency image with dominant directions": true,
    "Frequency image with filter": true,
    "Filter": true,
    "Filtered frequency image": true,
    "Polar frequency image": true,
    "Polar frequency histogram": true,
    "Polar frequency image and histogram": true,
    "Reconstructed map": true,
    "Scored map": true,
    "Filtered map overlay": true,
    "Filtered map final": true,
    "Cell histogram": true,
    "Map with directions": true,
    "Map with long wall lines": true
  }
}
